---
# tasks file for nginx
- name: Create a directory if it does not exist
  file:
    path: /etc/nginx/sites-available
    state: directory
    mode: '0755'
- name: Create a directory if it does not exist
  file:
    path: /etc/nginx/sites-enabled
    state: directory
    mode: '0755'
- name: nginx site config templating
  template:
    src: files/nginx.conf
    dest: /etc/nginx/sites-available/{{ app_name }}
- name: remove default nginx site config
  file: path=/etc/nginx/sites-enabled/default state=absent
- name: enable nginx site
  file:
    src: /etc/nginx/sites-available/{{ app_name }}
    dest: /etc/nginx/sites-enabled/default
    state: link
    force: yes
- name: restart nginx
  systemd: name=nginx state=restarted enabled=yes