---
# tasks file for webserver
- name: Enable epel for AmzLinux2
  become: yes
  command: amazon-linux-extras enable epel
- name: install packages
  yum: name={{item}} state=present
  with_items:
    - python3-pip
    - python3-devel
    - epel-release
    - nginx
    - git
# Install Application
- name: clone repo
  git:
    repo: 'https://github.com/{{ github_user }}/{{ app_name }}.git'
    dest: /home/{{ ansible_user }}/{{ app_name }}
    update: yes  # Does a git pull if the repo already exists
- name: Install modules in a virtualenv
  become: yes
  pip:
    requirements: /home/{{ ansible_user }}/{{ app_name }}/requirements.txt
    virtualenv: /home/{{ ansible_user }}/{{ app_name }}/env
    virtualenv_command: /usr/bin/python3 -m venv
- name: template systemd service config
  template:
    src: files/service.conf
    dest: /etc/systemd/system/{{ app_name }}.service
- name: start systemd app service
  systemd: name={{ app_name }}.service state=restarted enabled=yes
