---
- hosts: _kashley_Webserver
  gather_facts: yes
  vars:
    ansible_user: ssm-user
    ansible_connection: aws_ssm
    ansible_shell_type: sh
    ansible_aws_ssm_region: us-east-1
    ansible_aws_ssm_profile: default
    ansible_aws_ssm_bucket_name: kashley-ansible
  roles:
    - demo_app
    - nginx