---
- name: Security Group for EC2 Instance
    ec2_group:
      name: "{{ prefix }}-WebserverSG"
      description: Security Group for Web Server allowing port for http and ssh
      region: "{{ region }}"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 45.36.131.90/32 "{{ var }}"
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 45.36.131.90/32 "{{ var }}"
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 45.36.131.90/32 "{{ var }}"
      rules_egress:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0

- name: EC2 Instance for Webserver
    ec2:
      key_name: webkey
      instance_type: t2.micro
      image: ami-0e306788ff2473ccb "{{ ami }}"
      wait: true
      group: "{{ prefix }}-WebserverSG"
      count: 1
      vpc_subnet_id: subnet-6dfdc705 "{{ subnet_id}}"
      assign_public_ip: yes
      region: "{{ region }}"
      state: present
      instance_tags:
        Name: webserver {{ instance_name }}
        EnvName: “Test Environment” {{ env_name }}
    register: ec2
