---

## get ip of ansible instance running this playbook

## get vpc info of ansible instance running

- name: Security Group for EC2 access
  ec2_group:
    name: "{{ prefix }}-{{ instance_name }}SG"
    description: Security Group allowing port for http and ssh
    region: "{{ region }}"
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: "{{ access_ip }}"
    - proto: tcp
      from_port: 80
      to_port: 80
      cidr_ip: "{{ access_ip }}"
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: "{{ ansible_ip }}"
    rules_egress:
    - proto: tcp
      from_port: 80
      to_port: 80
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 443
      to_port: 443
      cidr_ip: 0.0.0.0/0
    tags:
        Name: "{{ prefix }}-{{ instance_name }}SG"
        owner: "{{ owner }}"
    vpc_id: "{{ vpc_id }}"
  register: security_group

- name: Create an EC2 key
  ec2_key:
    name: "{{ prefix }}-{{ instance_name }}-key"
    region: "{{ region }}"
  register: ec2_key

- name: Save private key
  copy: content="{{ ec2_key.key.private_key }}" dest="../aws-private.pem" mode=0600
  when: ec2_key.changed

- name: EC2 Instance
  ec2_instance:
    key_name: "{{ prefix }}-{{ instance_name }}-key"
    instance_type: "{{ instance_type }}"
    image_id: "{{ image_id }}"
    wait: true
    security_group: "{{ security_group.group_id }}"
    exact_count: "{{ instance_count }}"
    vpc_subnet_id: "{{ subnet_id }}"
    network:
      assign_public_ip: true
    region: "{{ region }}"
    state: running
    tags:
      Name: "{{ prefix }}-{{ instance_name }}"
      EnvName: "{{ env_name }}"
      owner: "{{ owner }}"
  register: ec2
- name: Display all variables/facts known for a host
  debug: var="ec2"

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip_address }}"
    groupname: webserver
  loop: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    state: started
  loop: "{{ ec2.instances }}"