---
# tasks file for webserver
- name: update cache
  apt: name=python-software-properties state=present update_cache=yes cache_valid_time=43200
- name: install packages
  apt: name={{item}} state=installed
  with_items:
    - python3-pip
    - python3-dev
    - nginx
- name: template systemd service config
  copy:
    src: files/service.conf
    dest: /etc/systemd/system/{{ app_name }}.service
- name: start systemd app service
  systemd: name={{ app_name }}.service state=restarted enabled=yes
